version: '{build}'

clone_folder: c:\gopath\src\gopkg.in\reform.v1

environment:
  GOPATH: c:\gopath
  COVERALLS_TOKEN:
    secure: +o9WB0T57udDJzTTSmKMg0O5hrP2e0rAuBL36/foBRYTg8VKccp2G8ovxJi4hsmD
  matrix:
    - REFORM_SQL_INSTANCE: SQL2008R2SP2
    - REFORM_SQL_INSTANCE: SQL2012SP1
    - REFORM_SQL_INSTANCE: SQL2014
    - REFORM_SQL_INSTANCE: SQL2016

install:
  - powershell -file .github\appveyor-prepare-mssql.ps1
  - set PATH=%PATH%;C:\msys64\mingw64\bin;%GOPATH%\bin

  - go version
  # - echo %PATH%
  # - go env
  # - where mingw32-make
  # - where gcc

build_script:
  - mingw32-make download_deps
  - mingw32-make install_deps

test_script:
  - mingw32-make test mssql sqlserver
  - mingw32-make check

on_success:
  - if defined COVERALLS_TOKEN goveralls -coverprofile=mssql.cover -service=
  - if defined COVERALLS_TOKEN goveralls -coverprofile=sqlserver.cover -service=
